-- Public submission queue + maintainer approve RPC

CREATE TYPE public.submission_form_mode AS ENUM ('basic', 'advanced');

CREATE TABLE public.sighting_submissions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamptz NOT NULL DEFAULT now(),
  form_mode public.submission_form_mode NOT NULL DEFAULT 'basic',
  username text,
  image_url text NOT NULL,
  anilist_link text,
  notes text,
  date_spotted date,
  title_en text,
  title_r text,
  title_jp text,
  episode text,
  timestamp text,
  lighthouse_type public.sighting_type DEFAULT 'fictional',
  lighthouse_id integer REFERENCES public.lighthouses (id),
  media_id text,
  media_type public.media_type DEFAULT 'anime',
  enrichment jsonb DEFAULT '{}'::jsonb,
  ip_hash text
);

ALTER TABLE public.sighting_submissions ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Maintainer read submissions"
  ON public.sighting_submissions
  FOR SELECT
  TO authenticated
  USING ((SELECT auth.uid()) = '27518d60-563d-427d-827e-74279a3b3ea5'::uuid);

CREATE POLICY "Maintainer delete submissions"
  ON public.sighting_submissions
  FOR DELETE
  TO authenticated
  USING ((SELECT auth.uid()) = '27518d60-563d-427d-827e-74279a3b3ea5'::uuid);

CREATE OR REPLACE FUNCTION public.approve_sighting_submission(
  p_submission_id bigint,
  p_sighting jsonb
)
RETURNS bigint
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_uid uuid;
  v_new_id bigint;
  v_links text[];
BEGIN
  v_uid := auth.uid();
  IF v_uid IS NULL OR v_uid <> '27518d60-563d-427d-827e-74279a3b3ea5'::uuid THEN
    RAISE EXCEPTION 'not authorized';
  END IF;

  IF NOT EXISTS (SELECT 1 FROM sighting_submissions WHERE id = p_submission_id) THEN
    RAISE EXCEPTION 'submission not found';
  END IF;

  SELECT array_agg(elem)
  INTO v_links
  FROM jsonb_array_elements_text(p_sighting->'image_link') AS elem
  WHERE trim(elem) <> '';

  IF v_links IS NULL OR array_length(v_links, 1) < 1 THEN
    RAISE EXCEPTION 'image_link required (upload an image before approving)';
  END IF;

  INSERT INTO sightings (
    date_spotted,
    title_en,
    title_r,
    title_jp,
    media_id,
    anilist_link,
    episode,
    timestamp,
    lighthouse_id,
    image_link,
    lighthouse_type,
    media_type,
    notes
  ) VALUES (
    COALESCE((p_sighting->>'date_spotted')::date, CURRENT_DATE),
    NULLIF(trim(p_sighting->>'title_en'), ''),
    NULLIF(trim(p_sighting->>'title_r'), ''),
    NULLIF(trim(p_sighting->>'title_jp'), ''),
    NULLIF(trim(p_sighting->>'media_id'), ''),
    NULLIF(trim(p_sighting->>'anilist_link'), ''),
    NULLIF(trim(p_sighting->>'episode'), ''),
    NULLIF(trim(p_sighting->>'timestamp'), ''),
    CASE
      WHEN (p_sighting->>'lighthouse_id') IS NULL OR trim(p_sighting->>'lighthouse_id') = ''
      THEN NULL
      ELSE (p_sighting->>'lighthouse_id')::integer
    END,
    v_links,
    COALESCE((p_sighting->>'lighthouse_type')::public.sighting_type, 'fictional'),
    COALESCE((p_sighting->>'media_type')::public.media_type, 'anime'),
    NULLIF(trim(p_sighting->>'notes'), '')
  )
  RETURNING id INTO v_new_id;

  DELETE FROM sighting_submissions WHERE id = p_submission_id;
  RETURN v_new_id;
END;
$$;

REVOKE ALL ON FUNCTION public.approve_sighting_submission(bigint, jsonb) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.approve_sighting_submission(bigint, jsonb) TO authenticated;
